apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          command: ['/bin/sh']
          args: ['-c', 'while true; do tail -f /var/log/syslog; done']
          resources:
            requests:
              memory: '32Mi'
              cpu: '100m'
            limits:
              memory: '64Mi'
              cpu: '200m'
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
