apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  selector:
    app: multi-container-app
  ports:
    - name: http-nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: http-echoserver
      protocol: TCP
      port: 9002
      targetPort: 8080
