apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-busybox
  template:
    metadata:
      labels:
        app: multitool-busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['/bin/sh']
          args:
            ['-c', 'while true; do date > /mnt/data/date.txt; sleep 5; done']
          resources:
            requests:
              memory: '32Mi'
              cpu: '100m'
            limits:
              memory: '64Mi'
              cpu: '200m'
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/data
        - name: multitool
          image: praqma/network-multitool
          resources:
            requests:
              memory: '32Mi'
              cpu: '100m'
            limits:
              memory: '64Mi'
              cpu: '200m'
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: local-pvc
