apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    pod-name: netology-web
spec:
  containers:
    - name: echoserver
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      resources:
        limits:
          cpu: '1'
          memory: '512Mi'
        requests:
          cpu: '0.5'
          memory: '256Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    pod-name: netology-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
