apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      resources:
        requests:
          cpu: '100m'
          memory: '64Mi'
        limits:
          cpu: '200m'
          memory: '128Mi'
